twitter_username: mibaltoalex
github_username:  mibaltoalex
gitlab_username:  mibaltoalex
author: Miguel J. Carmona
version: 2021.12.20.1211
title: MIBALTOALEX
email: support@mibaltoalex.com
description: MIBALTOALEX APP
baseurl: ""
url: "/"
webrick:
  headers:
    server: mws
    X-Ray-MWS: mws-proto-mbx-1
theme: minima
sass:
    load_paths:
        - _sass
        - node_modules
    style: compressed
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - start.bat
   - package.json
   - gulpfile.js
   - README.md
