twitter_username: mibaltoalex
github_username:  mibaltoalex
gitlab_username:  mibaltoalex
author: Miguel J. Carmona
version: 2022.04.29.1808
title: MIBALTOALEX
email: support@mibaltoalex.com
description: MIBALTOALEX APP
domain: app.mibaltoalex.com
url: https://app.mibaltoalex.com
webrick:
  headers:
    server: mws
    X-Ray-MWS: mws-proto-mbx-1
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [head, body]
sass:
    load_paths:
        - _sass
        - node_modules
    style: compressed
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - start.bat
   - package.json
   - gulpfile.js
   - README.md
